"""Increase password_hash length to 256

Revision ID: 050900d06cc1
Revises: 020e0a23eb9a
Create Date: 2025-07-11 13:57:55.303701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050900d06cc1'
down_revision = '020e0a23eb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
